/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ffe299",
        "primary-container": "#f5c200",
        "on-primary": "#3d2e00",
        "background": "#1A1A1A",
        "surface": "#1A1A1A",
        "surface-dim": "#1A1A1A",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#20201f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#d2c5ab",
        "outline": "#9b9078",
        "outline-variant": "#4e4632",
        "secondary": "#c6c6c7",
        "secondary-container": "#454747",
        "on-secondary": "#2f3131",
        "on-secondary-container": "#b4b5b5",
        "tertiary": "#baedff",
        "tertiary-container": "#49d9ff",
        "on-tertiary": "#003642",
        "on-tertiary-container": "#005c70",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-xl": ["Oswald", "sans-serif"],
        "headline-lg": ["Oswald", "sans-serif"],
        "headline-md": ["Oswald", "sans-serif"],
        "headline-lg-mobile": ["Oswald", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
